umask 022

#if test -d /etc/profile.d; then
#	for profile in /etc/profile.d/*.sh; do
#		test -r "$profile" && . "$profile"
#	done
#	unset profile
#fi

unset TERMCAP
unset MANPATH

sudo mount -t ntfs /dev/sda8 /mnt/ntfs

sudo /usr/sbin/wpa_supplicant -Dwext -i wlan0 -c /etc/wpa_supplicant.conf -B
sudo /sbin/dhcpcd wlan0
