export PS1='%~ %#] '
export CLASSPATH="$CLASSPATH:/usr/share/clojure/clojure.jar:./"
export EDITOR='/usr/bin/nano'
export PATH="/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:$HOME/bin"
