setopt ALL_EXPORT
setopt APPEND_HISTORY
setopt EXTENDED_HISTORY
setopt MENU_COMPLETE

autoload -U colors && colors

PS1="%B[%b%{$fg_bold[red]%}%n%{$reset_color%}@%{$fg_bold[green]%}%m %{$fg_bold[blue]%}%~%{$reset_color%}%B]%b "
HISTFILE=$HOME/.zhistory
HISTSIZE=1000
SAVEHIST=1000
